### PR TITLE
Add config setting to control line wrapping and bump version number

### PR DESCRIPTION
**Pull request by adrianbj**

### CODE REVIEW

**Comment by adrianbj** [comment]
I set the default to `off` just because that is the codemirror default, but obviously if you feel strongly, I don't mind if you want to make it `on`

**Comment by matjazpotocnik** [comment]
Thank you for PR. Yeah, I went for `on` as this was the default.

**Comment by adrianbj** [comment]
Did they change the default recently?

The docs read:

> lineWrapping: boolean
> Whether CodeMirror should scroll or wrap for long lines. Defaults to false (scroll).

Anyway, whatever you are happy with is fine. Thanks for incorporating!

**Comment by matjazpotocnik** [comment]
I mean it was `on` in this module and don't want to change that default ...

**Comment by adrianbj** [comment]
> I mean it was on in this module and don't want to change that default ...

Right, sorry I misunderstood.

Thanks again!

**Pull request merged**
